triggerFramework/main/default/objects/TriggerConfig__mdt/TriggerConfig__mdt.object-meta.xml
<CustomObject>
    <description>Binds implementation of the ITriggerHandler (or ITriggerSimpleHandler) to an sObject</description>
    <label>TriggerConfig</label>
    <pluralLabel>TriggerConfigs</pluralLabel>
</CustomObject>

triggerFramework/main/default/objects/TriggerConfig__mdt/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <description>Name of the implementation class</description>
    <label>Class Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

triggerFramework/main/default/objects/TriggerConfig__mdt/fields/TriggerSObject__c.field-meta.xml
<CustomField>
    <fullName>TriggerSObject__c</fullName>
    <description>Binding to sObject on which to execute the trigger handler</description>
    <label>Trigger sObject</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>TriggerConfigs</relationshipLabel>
    <relationshipName>TriggerConfigs</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

triggerFramework/main/default/classes/TriggerDispatcher_Test.cls
@isTest 
private class TriggerDispatcher_Test {
    @isTest 
    static void testCoverage() {
        TriggerDispatcher.runTriggers = false;

        Test.startTest();
        try {
            new TriggerDispatcher(Account.getSObjectType()).runTriggerHandlers();
        }
            catch (Exception e) {            
        }
        Test.stopTest();        
    }

    @isTest 
    static void testCoverageMore() {
        TriggerDispatcher.runTriggers = false;
        
        // prettier-ignore
        String metadataJsonString = '{' +
            '"attributes": {' +
              '"type": "TriggerConfig__mdt",' +
              '"url": "/services/data/v49.0/sobjects/TriggerConfig__mdt/m001j0000005rBhAAI"' +
            '},' +
            '"DeveloperName": "Test",' +
            '"ClassName__c": "AccountTriggerHandler",' +
            '"TriggerSObject__c": "Account",' +
            '"Id": "m001j0000005rBhAAI"' +
          '}';

        Test.startTest();
        try {
            TriggerDispatcher dispatcher = new TriggerDispatcher(Account.getSObjectType());
            dispatcher.handlerConfigs.add((TriggerConfig__mdt) JSON.deserialize(metadataJsonString, Schema.TriggerConfig__mdt.class));
            dispatcher.runTriggerHandlers();
        }
        catch (Exception e) {            
        }
        Test.stopTest();        
    }
}